CSRazorSolution/WebApp/Pages/Samples/BasicDataManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Samples
{
    public class BasicDataManagementModel : PageModel
    {
        // BindProperty is an annotation that handles two-way data transfer
        // two-way? means output to form for display AND input from form for processing
        [BindProperty]
        public int Num { get; set; }
        [BindProperty]
        public string MassText { get; set; }
        [BindProperty]
        public int FavouriteCourse { get; set; }

        // Feedback is just for display, doesn't need a BindProperty on it.
        public string Feedback { get; set; }
        public string ErrorMsg { get; set; }
        public void OnGet()
        {
            if(Num == 0)
            {
                Feedback = "executing the OnGet method for the Get request";
            }
            else
            {
                Feedback = $"You entered the value {Num} displayed by OnGet";
            }
        }

        public void OnPost()
        {
            if (Num == 0)
            {
                Feedback = "executing the OnPost method for a value of zero";
            }
            else
            {
                Feedback = $"You entered the value {Num} (displayed by OnPost)" +
                $" your mass text is {MassText} and I like the {FavouriteCourse} course";
            }
        }
        public void OnPostSecondButton()
        {
            if (Num == 0)
            {
                Feedback = "executing the OnPostSecondButton method for a value of zero";
            }
            else if(FavouriteCourse == 0)
            {
                Feedback = "You did not select a favourite course.";
            }
            else
            {
                Feedback = $"You entered the value {Num} (displayed by OnPostSecondButton)" +
                $" your mass text is {MassText} and I like the {FavouriteCourse} course";
            }
        }
    }
}

CSRazorSolution/WebApp/Pages/Samples/CategoryProducts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;       //this is where the services were coded
using WestWindSystem.Entities;  //this is where the entity definition is coded
using WebApp.Helpers;
#endregion

namespace WebApp.Pages.Samples
{
    public class CategoryProductsModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly CategoryServices _categoryServices;
        private readonly ProductServices _productServices;

        public CategoryProductsModel(CategoryServices categoryyservices,
                                        ProductServices productservices)
        {
            _categoryServices = categoryyservices;
            _productServices = productservices;
        }
        #endregion
        //  this property is being used as the routing parameter
        //  the SupportsGet = true indicates that the parameter
        //      supports the OnGet issued by the RedirectToPage
        [BindProperty(SupportsGet = true)]
        public int? categoryid { get; set; }

        public List<Category> CategoryList { get; set; }
        
        /// <summary>
        /// why Feedback needs to be carried to the web page which will call
        ///     the OnGet (second trip to server) to obtain the data to display
        ///     on the browser.
        /// </summary>
        [TempData]
        public string Feedback { get; set; }
        public void OnGet()
        {
            PopulateLists();
        }

        public void PopulateLists()
        {
            CategoryList = _categoryServices.Category_List();
        }

        public IActionResult OnPostSearch()
        {
            if(categoryid == 0)
            {
                Feedback = "Select a category to view the products for maintenance";
            }
            return RedirectToPage(new {categoryid = categoryid});
        }
        public IActionResult OnPostClear()
        {
            Feedback = "";
            categoryid = 0;
            ModelState.Clear();
            return RedirectToPage(new { categoryid = categoryid });
        }
    }
}

CSRazorSolution/WebApp/Pages/Samples/Controls.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages.Samples
{
    public class ControlsModel : PageModel
    {
        [TempData]
        public string Feedback { get; set; }

        [BindProperty]
        public string EmailText { get; set; }
        [BindProperty]
        public string PasswordText { get; set; }
        [BindProperty]
        public string DateTimeText { get; set; }

        [BindProperty]
        public string RadioMeal { get; set; }
        public string[] RadioMeals = new[] { "breakfast", "lunch", "dinner/supper", "snacks" };

        [BindProperty]
        public bool AcceptanceBox { get; set; } //remember value=true on input control

        [BindProperty]
        public string MessageBody { get; set; }

        [BindProperty]
        public int MyRide { get; set; }
        //pretend the collection is coming from the database
        //each row of the collection has two values: selection value; selection text
        //the class SelectionList will be use as the datatype for the collection
        public List<SelectionList> Rides { get; set; }

        [BindProperty]
        public string VacationSpot { get; set; }
        public List<string> VacationSpotList { get; set; }

        [BindProperty]
        public int RangeValue { get; set; }
        
        public void OnGet()
        {
            PopulateLists();
        }

        public void PopulateLists()
        {
            //pretending that this data comes from the database
            Rides = new List<SelectionList>();
            Rides.Add(new SelectionList() { ValueId = 3, DisplayText="Bike" });
            Rides.Add(new SelectionList() { ValueId = 5, DisplayText="Board" });
            Rides.Add(new SelectionList() { ValueId = 2, DisplayText="Bus" });
            Rides.Add(new SelectionList() {ValueId = 1, DisplayText="Car" });
            Rides.Add(new SelectionList() { ValueId = 4, DisplayText="Motorcycle" });

            VacationSpotList = new List<string>();
            VacationSpotList.Add("California");
            VacationSpotList.Add("Caribbean");
            VacationSpotList.Add("Cruising");
            VacationSpotList.Add("Europe");
            VacationSpotList.Add("Florida");
            VacationSpotList.Add("Mexico");

        }
        public IActionResult OnPostText()
        {
            //this method is tied to the specific button on the form via
            //  the asp-page-handler attribute.
            //the form of the method name is OnPost then concatenate the
            //  value given to the handler attribute

            Feedback = $"Email {EmailText}; Password {PasswordText}; Date {DateTimeText}";
            PopulateLists();
            return Page();
        }

        public IActionResult OnPostRadioCheckArea()
        {
            Feedback = $"Meal {RadioMeal}; Acceptance {AcceptanceBox}; Message {MessageBody}";
            PopulateLists();
            return Page();
        }

        public IActionResult OnPostListSlider()
        {
            Feedback = $"Ride {MyRide}; Vacation {VacationSpot}; Review Satification {RangeValue}";
            PopulateLists();
            return Page();
        }

    }

    public class SelectionList
    {
        //common class used to hold 2 values for use in a select list scenario such
        //  as a drop down list
        public int ValueId { get; set; }
        public string DisplayText { get; set; }
    }

}

CSRazorSolution/WebApp/Pages/Samples/PartialFilterSearch.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;       //this is where the services were coded
using WestWindSystem.Entities;  //this is where the entity definition is coded
#endregion


namespace WebApp.Pages.Samples
{
    public class PartialFilterSearchModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly TerritoryServices _territoryServices;
        private readonly RegionServices _regionServices;

        public PartialFilterSearchModel(TerritoryServices territoryservices,
                                        RegionServices regionservices)
        {
            _territoryServices = territoryservices;
            _regionServices = regionservices;
        }
        #endregion

        [TempData]
        public string Feedback { get; set; }

        [BindProperty(SupportsGet = true)]
        public string searcharg { get; set; }

        public List<Territory> TerritoryInfo { get; set; }

        [BindProperty]
        public List<Region> RegionList { get; set; } = new();

        public void OnGet()
        {
            PopulateLists();
            //check to see if there is a search arg before doing the call to the service
            if(!string.IsNullOrWhiteSpace(searcharg))
            {
                TerritoryInfo = _territoryServices.GetByPartialDescription(searcharg);
            }
        }

        public void PopulateLists()
        {
            RegionList = _regionServices.Region_List();
        }

        public IActionResult OnPostFetch()
        {
            if (string.IsNullOrWhiteSpace(searcharg))
            {
                Feedback = "Required: Search argument is empty.";
            }

            return RedirectToPage(new { searcharg = searcharg });
        }

        public IActionResult OnPostClear()
        {
            Feedback = "";
            searcharg = null;
            ModelState.Clear();
            return RedirectToPage(new { searcharg = (string?)null });
        }

        public IActionResult OnPostNew()
        {
            return RedirectToPage("/Samples/ReceivingPage");
        }

    }
}

CSRazorSolution/WebApp/Pages/Samples/PartialFilterSearchPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;       //this is where the services were coded
using WestWindSystem.Entities;  //this is where the entity definition is coded
using WebApp.Helpers;
#endregion


namespace WebApp.Pages.Samples
{
    public class PartialFilterSearchPageModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly TerritoryServices _territoryServices;
        private readonly RegionServices _regionServices;

        public PartialFilterSearchPageModel(TerritoryServices territoryservices,
                                        RegionServices regionservices)
        {
            _territoryServices = territoryservices;
            _regionServices = regionservices;
        }
        #endregion

        public string Feedback { get; set; }

        [BindProperty]
        public string searcharg { get; set; }

        public List<Territory> TerritoryInfo { get; set; }

        //the List<T> has a null value as the page is created
        //you can initialize the property to an instance as the page is
        //      being created by adding = new() to your declaration
        //if you do, you will have an empty instance of List<T>
        [BindProperty]
        public List<Region> RegionList { get; set; } = new();

        #region Paginator
        //my desired page size
        private const int PAGE_SIZE = 5;
        //be able to hold an instance of the Paginator
        public Paginator Pager { get; set; }

        #endregion

        public void OnGet(int? currentPage)
        {
            PopulateLists();

            //the paginator will call this OnGet() method
            //the requested page enters the method via currentPage

            PopulateTable(currentPage);

        }

        public void PopulateTable(int? currentPage)
        {
            if (!string.IsNullOrWhiteSpace(searcharg))
            {
                //setting up for using the Paginator only needs to be done if
                //  a query is executing

                //determine the current page number
                int pagenumber = currentPage.HasValue ? currentPage.Value : 1;
                //setup the current state of the paginator (sizing)
                PageState current = new(pagenumber, PAGE_SIZE);
                //temporary local integer to hold the results of the query's total collection size
                //  this will be need by the Paginator during the paginator's execution
                int totalcount;

                //we need to pass paging data into our query so that efficiencies in the
                //  system will ONLY return the amount of records to actually be display
                //  on the browser page.

                TerritoryInfo = _territoryServices.GetByPartialDescription(searcharg,
                                    pagenumber, PAGE_SIZE, out totalcount);

                //create the needed Pagnator instance
                Pager = new Paginator(totalcount, current);
            }
        }
        public void PopulateLists()
        {
            RegionList = _regionServices.Region_List();
        }

        public IActionResult OnPostFetch()
        {
            if (string.IsNullOrWhiteSpace(searcharg))
            {
                Feedback = "Required: Search argument is empty.";
            }
            else
            {
                //this needs to be commented out ONCE you have installed paging in the
                //      RedirecToPage version of this example.

                //TerritoryInfo = _territoryServices.GetByPartialDescription(searcharg);
                PopulateTable(1);
            }
            return Page();
        }

        public IActionResult OnPostClear()
        {
            Feedback = "";
            searcharg = null;
            ModelState.Clear();
            return Page();
        }

        public IActionResult OnPostNew()
        {
            return RedirectToPage("/Samples/ReceivingPage");
        }

    }
}

CSRazorSolution/WebApp/Pages/Samples/RegionQueryOne.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#region Additional Namespaces
using WestWindSystem.BLL;       //this is where the services were coded
using WestWindSystem.Entities;  //this is where the entity definition is coded
#endregion


namespace WebApp.Pages.Samples
{
    public class RegionQueryOneModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly RegionServices _regionServices;

        public RegionQueryOneModel(RegionServices regionservices)
        {
            _regionServices = regionservices;
        }
        #endregion

        public string FeedbackMessage { get; set; }

        //this is bond to the input control via asp-for
        //this is a two way binding out and in
        //data is move out and in FOR YOU AUTOMATICALLY
        [BindProperty()]
        public int regionid { get; set; }

        public Region regionInfo { get; set; }

        //the List<T> has a null value as the page is created
        //you can initialize the property to an instance as the page is
        //      being created by adding = new() to your declaration
        //if you do, you will have an empty instance of List<T>
        [BindProperty]
        public List<Region> regionsList { get; set; } = new();

        [BindProperty]
        public int selectRegion { get; set; }

        public void OnGet()
        {
            //since the internet is a stateless environment, you need to 
            //  obtain any list data that is required by your controls or local
            //  logic on EVERY instance of the page being processed
            PopulateLists();

        }

        private void PopulateLists()
        {
            //this method will obtain the data for any require list to be used
            //      in populating controls or for local logic
            regionsList = _regionServices.Region_List();
        }

        

        // specific post method to use in conjunction with asp-page-handler="xxx"
        public IActionResult OnPostFetch()
        {
            if (regionid < 1)
            {
                FeedbackMessage = "Required: Region id is a non-zero positive whole number.";
            }
            

            else
            {
                RetrieveRegion(regionid);
            }
            PopulateLists();
            
            return Page();
        }

        public IActionResult OnPostSelect()
        {
            if (selectRegion < 1)
            {
                FeedbackMessage = "Required: Region id is a non-zero positive whole number.";
            }


            else
            {
                RetrieveRegion(selectRegion);
            }
            PopulateLists();

            return Page();
        }
        // specific post method to use in conjunction with asp-page-handler="xxx"
        public IActionResult OnPostClear()
        {
            FeedbackMessage = "";
            regionid = 0;
            ModelState.Clear();
            PopulateLists();
            return Page();
        }
        public void RetrieveRegion(int id)
        {
            regionInfo = _regionServices.Region_GetByID(id);
            if (regionInfo == null)
            {
                FeedbackMessage = "Region id is not valid. No such region on file";
            }
            else
            {
                FeedbackMessage = $"ID: {regionInfo.RegionID} Description: {regionInfo.RegionDescription}";
            }
        }
    }
}

CSRazorSolution/WebApp/Pages/Samples/Controls.cshtml
@page
@model WebApp.Pages.Samples.ControlsModel
@{
    ViewData["Title"] = "Various Controls";
}

@*embedded css*@
@*<style>
    :root {
        --max-body-width: 90rem;
    }

    .setflex {
        display: flex;
    }

    .onethird{
        width: 31%;
        margin-right: 2%;
    }

    .onehalf {
        width: 47%;
        margin-right: 3%;
    }

    .smallbox {
        width: 60px;
    }

    .bighalfpage {
        width: 57%;
        margin-right: 3%;
    }

    .smallhalfpage {
        width: 37%;
        margin-right: 3%;
    }

    .lefthalfpage {
        width: 45%;
        margin-right: 5%;
    }

    .righthalfpage {
        width: 45%;
        margin-left: 5%;
    }

    .danger {
        color: var(--danger-text-color);
        background-color: var(--danger-color);
    }
</style>*@

<h1>Various Form Controls</h1>

@if (!string.IsNullOrWhiteSpace(Model.Feedback))
{
    <p>@Model.Feedback</p><br/>
}

<section class="setflex">
    <div class="onethird">
        <h3>TextBoxes</h3>
        <form method="post">
            <label>
                Email input
                <input type="email" asp-for="EmailText"
                    placeholder="enter email"/>
            </label>
            <br/>
            <label>
                Password input
                <input type="password" asp-for="PasswordText"
                    placeholder="enter password"/>
            </label>
            <br/>
            <label>
                Date input
                <input type="date" asp-for="DateTimeText"
                    placeholder="enter a date"/>
            </label>
            <br/>
            <button type="submit" value="textbox" id="theTextButton"
                name="theTextButton" asp-page-handler="Text">Text Submit</button>
        </form>
    </div>
    <div class="onethird">
        <h3>RadioButton, CheckBox and TextArea</h3>
        <form method="post">
            <label>
                Select favourite meal<br/>
            </label>
            <input type="radio" asp-for="RadioMeal" value="breakfast"/>
                &nbsp;Breakfast<br/>
            <input type="radio" asp-for="RadioMeal" value="lunch"/>
                &nbsp;Lunch<br/>
            <input type="radio" asp-for="RadioMeal" value="dinner/supper"/>
                &nbsp;Dinner/Supper<br/>
            <input type="radio" asp-for="RadioMeal" value="snacks"/>
                &nbsp;Snacks<br/>
            
            @*@foreach(var item in Model.RadioMeals)
            {
                <input type="radio" asp-for="RadioMeal" value="@item"/> @item<br/>
            }*@
            <br/>
            <label>
                @*value=true is you want the value to come back as true or false.
                    otherwise it returns On (true) or null.
                *@
                <input type="checkbox" asp-for="AcceptanceBox" value=true />
                    &nbsp; I agree to the terms
            </label>
            <br/>
            <label>
                Message
                <textarea rows="5" cols="60" placeholder="enter a message"
                    asp-for="MessageBody">@Model.MessageBody</textarea>
            </label>
            <br/>
            <button type="submit" value="radiocheckarea" id="theRadioCheckAreaButton"
                name="theRadioCheckAreaButton" asp-page-handler="RadioCheckArea">
                Radio/Check/Area Submit</button>
        </form>
    </div>
    <div class="onethird">
        <h3>Lists and Slider</h3>
        <form method="post">
            <label>
                Select favourite Ride<br/>
                <select asp-for="MyRide">
                    <option value="0">select a ride ...</option>
                    @foreach(var item in Model.Rides)
                    {
                        <option value="@item.ValueId">@item.DisplayText</option>
                    }
                </select>
            </label>
            <br/>
            <label>
                Select favourite Vacation Spot
                <input type="text" asp-for="VacationSpot"
                    list = "VacationChoices" />
                <datalist id="VacationChoices">
                    @foreach(var item in Model.VacationSpotList)
                    {
                        //use if expected value is the same as the display value
                        <option value="@item"/>

                    @*   use if the expected value is different then the display value
                         this setup is the same as the drop down list

                        <option value="@item.expectedvalue">@item.displayvalue</option>*@ 
                   }
                </datalist>
            </label>
            <br/>
            <label>
                Review of controls (bad < - > good)
                <input type="range" min="0" max="10" steps="1" value="5"
                    asp-for="RangeValue" checked="@Model.RangeValue" />
            </label>
            <br/>
                <button type="submit" value="listslider" id="theListSliderButton"
                name="theListSliderButton" asp-page-handler="ListSlider">
                List/Slider Submit</button>

        </form>
    </div>
</section>

CSRazorSolution/WebApp/Pages/Samples/PartialFilterSearch.cshtml
@page "{searcharg?}"
@model WebApp.Pages.Samples.PartialFilterSearchModel
@{
    ViewData["Title"] = "Partial String Table Query";
}
<h1>Partial String query resulting in a Table display</h1>

<p>@Model.Feedback</p>

<form method="post">
    <label>
        Enter a partial Territory description:
        <input type="text" asp-for="searcharg"
            placeholder="enter your description"/>
    </label>
    <br/>
    @*restrict the display of the table to when there is data to view
        The first IF checks to see if an instance of TerritoryInfo actually exists
    *@
    @if (Model.TerritoryInfo != null)
    {
        @*This IF checks to see if any records were found when the query was executing*@
        if (Model.TerritoryInfo.Count == 0)
        {
            <p style="color:blueviolet; font-weight:bold; font-size:large;">
                There are no territories matching your search request.
            </p>
        }
        else
        {
            @*
                Records have been found to display
                The number of records is unknown
                Use a tabular (grid table) layout to display the records
                Use the <table> tag and its components <thead>, <tbody>, <tfoot>
            *@
            <table>
                <thead>
                    @*used for column titles*@
                    <tr>
                        <th>Territory</th>
                        <th>Name</th>
                        <th>Region</th>
                    </tr>
                </thead>
                <tbody>
                    @*used for the table details
                        the number of rows are unsually unknown for a db query
                    *@
                    @foreach (var item in Model.TerritoryInfo)
                    {
                        <tr>
                            <td>
                                @*
                                    this example will send the TerritoryID to
                                    another page
                                    use the anchor tag to accomplish this task
                                    the href page value MUST be reference from
                                       the Page folder
                                    the value to be passed is attached to the
                                       end of the page reference
                                    In this example, the value will be passed
                                       to the receivng page as a routing parameter
                                    You CAN send multiple values to the new page
                                    The receiving page MUST have the same number of
                                       routing parameters as those past AND the 
                                       order of the routing parameters is IMPORTANT
                                    Page reference syntax: /pathname/value[/value/...]
                                    The text of your anchor tag DOES NOT need to be
                                       the value that is being passed
                                *@
                                <a href="/Samples/ReceivingPage/@item.TerritoryID">
                                    Edit this territory
                                </a>
                                
                                @*<a href="/Samples/ReceivingPage?tid=@item.TerritoryID">
                                    Edit this territory
                                </a>*@
                            </td>
                            <td>@item.TerritoryDescription</td>
                            <td><select disabled="true">
                                    @foreach (var region in Model.RegionList)
                                    {
                                        if (region.RegionID == item.RegionID)
                                        {
                                            <option value="@region.RegionID" selected>@region.RegionDescription</option>
                                        }
                                        else
                                        {
                                            <option value="@region.RegionID">@region.RegionDescription</option>
                                        }
                                    }
                                </select> 
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                 @*used for summay table information eg totals
                   used for displaying paging information                                       
                 *@
                    
                </tfoot>
            </table>
        }
    }
    <button type="submit" asp-page-handler="Fetch">Fetch Territories</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="New" formnovalidate>New Territory</button>

</form>

CSRazorSolution/WebApp/Pages/Samples/ReceivingPage.cshtml
@page "{territoryid?}"
@model WebApp.Pages.Samples.ReceivingPageModel
@{
    ViewData["Title"] = "Receiving passed data";
}
<h1>Receiving Pass of passed data</h1>

@if(Model.territoryid == null)
{
    <p>No value was passed &gt;@Model.territoryid&lt;</p>
}
else
{

<p>The value you passed was @Model.territoryid</p>
}

CSRazorSolution/WebApp/Pages/Samples/RegionQueryOne.cshtml
@page
@model WebApp.Pages.Samples.RegionQueryOneModel
@{
    ViewData["Title"] = "PKey Region Query";
}
<h1>Query: Region query by primary key</h1>

<p>@Model.FeedbackMessage</p>

<form method="post">
    <label>
        @* the type attribute can be set to different input for acceptable value
            "number" restricts input to numerics
            the numerics are by default whole numbers
            the numberics can be negative or positive
           additional attributes can be used to refine the acceptable values
            min="xxx" indicates the minumum acceptable value
            max="xxx" indicates the maximum acceptable value
            step="xxx" indicates the increments of the acceptable values
                step="1" (default) whole numbers increments of 1 (1,2,3,...)
                step="0.01" decimal numbers increments of .01 (great for $ amounts)
            required indicates that the field must have a value

            When you use these validation attributes on your form input controls
                the user MUST meet the validation BEFORE the form is sent to the
                web server for processing

            the attribute formnovalidate overrides any validation (html5) that exists
                on your form controls
        *@
        Enter Region ID:
        <input type="number" asp-for="regionid" style="width:80px"
            placeholder="enter your region id number"
            step="1" required/>
    </label>
    <label>
        Select a Region:
        <select asp-for="selectRegion" style="width:250px;">
            @* if you do not indicate a specific option to display
                 then the list defaults to the first option line
            *@
            <option value="0">select ... </option>
            @foreach(var item in Model.regionsList)
            {
                //to retain the selection, you need to specify a row to be
                //  the selected option
                //this is done with the selected attribute on the value 
                if (item.RegionID == Model.selectRegion)
                {
                    <option value="@item.RegionID" selected>@item.RegionDescription</option>

                }
                else
                {
                    <option value="@item.RegionID">@item.RegionDescription</option>
                }
            }
        </select>
    </label>
    <br/>
    <button type="submit" asp-page-handler="Fetch">Fetch By Id</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="Select" formnovalidate>Select By Description</button>&nbsp;&nbsp;
    <button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>
</form>